create table public.contact (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now (),
  email text not null,
  phone text null,
  message text null,
  name text not null,
  constraint contact_pkey primary key (id)
) TABLESPACE pg_default;

ALTER TABLE
  public.contact ENABLE ROW LEVEL SECURITY;

create policy "allow_all_inserts" on "public"."contact" to public with check (true);